desc "Discord notification"
lane :discord do
  discord_notifier(
    webhook_url: ENV["DISCORD_WEBHOOK"],
    title: "Finished building",
    description: "Success all test",
    success: true,
    thumbnail_url:"https://i.pinimg.com/originals/d7/8d/41/d78d41791cb125f6512c542dd0ee3837.gif",
  )
end

desc "Build for testing"
lane :build_for_testing do
  clear_derived_data(derived_data_path: "#{ENV['PWD']}/DerivedData/")
  cocoapods
  scan(derived_data_path: "DerivedData", build_for_testing: true)
end

desc "Run tests"
lane :run_tests do
  scan(derived_data_path: "DerivedData", test_without_building: true)
end

desc "Build and run tests"
lane :build_and_test do
  build_for_testing
  run_tests
  discord
end

