# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fintech_chat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for fintech_chat
  pod 'Firebase/Firestore'
  pod 'SwiftLint'

  target 'fintech_chat Tests' do
    inherit! :search_paths
  end

end
